-- Autocmds are automatically loaded on the VeryLazy event
-- Default LazyVim autocmds: https://github.com/LazyVim/LazyVim/blob/main/lua/lazyvim/config/autocmds.lua
-- Custom autocmds are added in Task 7.
