-- Options are automatically loaded before lazy.nvim startup
-- Default LazyVim options: https://github.com/LazyVim/LazyVim/blob/main/lua/lazyvim/config/options.lua
-- Custom options are added in Task 7.
