-- Text-only icon set. Overrides LazyVim's central `icons` table (which assumes
-- a nerd font) with plain ASCII, so the statusline, gutter, diagnostics,
-- which-key, and completion menu show letters/symbols instead of glyphs.
-- Pairs with `vim.g.have_nerd_font = false` in lua/config/options.lua.
return {
  {
    "LazyVim/LazyVim",
    opts = {
      icons = {
        misc = {
          dots = "...",
        },
        ft = {
          octo = "",
          gh = "",
          ["markdown.gh"] = "",
        },
        dap = {
          Stopped = { "->", "DiagnosticWarn", "DapStoppedLine" },
          Breakpoint = "B",
          BreakpointCondition = "C",
          BreakpointRejected = { "R", "DiagnosticError" },
          LogPoint = ".>",
        },
        diagnostics = {
          Error = "E ",
          Warn = "W ",
          Hint = "H ",
          Info = "I ",
        },
        git = {
          added = "+ ",
          modified = "~ ",
          removed = "- ",
        },
        kinds = {
          Array = "[] ",
          Boolean = "b ",
          Class = "C ",
          Codeium = "ai ",
          Color = "c ",
          Control = "ctl ",
          Collapsed = "> ",
          Constant = "const ",
          Constructor = "new ",
          Copilot = "ai ",
          Enum = "E ",
          EnumMember = "e ",
          Event = "ev ",
          Field = "f ",
          File = "F ",
          Folder = "D ",
          Function = "fn ",
          Interface = "I ",
          Key = "k ",
          Keyword = "kw ",
          Method = "m ",
          Module = "M ",
          Namespace = "ns ",
          Null = "0 ",
          Number = "# ",
          Object = "o ",
          Operator = "op ",
          Package = "pkg ",
          Property = "p ",
          Reference = "& ",
          Snippet = "snip ",
          String = "s ",
          Struct = "St ",
          Supermaven = "ai ",
          TabNine = "ai ",
          Text = "t ",
          TypeParameter = "T ",
          Unit = "u ",
          Value = "v ",
          Variable = "var ",
        },
      },
    },
  },
}
